twig:
    default_path: '%kernel.project_dir%/src/Presentation/Template'
    file_name_pattern: '*.twig'
    paths:
        'src/Presentation/Template': 'app'
        'src/Presentation/Template/Admin': 'admin'
        'src/Presentation/Template/reports': 'reports'
        'src/Presentation/Template/turbo': 'turbo'
        'src/Presentation/Template/macro': 'macro'

when@test:
    twig:
        strict_variables: true
